theme: jekyll-theme-minimal
# remote_theme: mmistakes/so-simple-theme
# skin: "/assets/css/skins/default.css"
locale: en-US
title: "Felicia Hester"
description: "Connecting data dots using Python & Excel formulas. Telling the data story using logic & creativity."
baseurl: "/portfolio" # the subpath of your site, e.g. "/blog"
url: "https://feliciahester.github.io/" # the base hostname & protocol for your site e.g. "https://feliciahester.github.io/"
logo: "/assets/FeliciaHester_ProfilePhoto.jpeg" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
enable: true
combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Helvetica Neue"
    weights: "400,400i,700,700i"
  - name: "Helvetica Neue"
    weights: "400,400i,700,700i"
# google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
# collections:
#  recipes:
#    output: true
#    permalink: /:collection/:path/

# Front Matter Defaults
# defaults:
  # Post defaults
#  - scope:
#      path: "_posts"
#      type: posts
#    values:
#      layout: post
#      comments: true
#      share: true
  # Recipe defaults
#  - scope:
#      path: "_recipes"
#      type: recipes
#    values:
#      layout: post
#      comments: true
#      share: true

# Site Author
author:
  name: Felicia Hester
  picture: /assets/FeliciaHester_ProfilePhoto.jpeg
  links:
    - title: GitHub
      url: https://feliciahester.github.io/portfolio/
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: GitHub
    url: https://feliciahester.github.io/portfolio/
    icon: fab fa-github-square
 
