title: Felicia Hester
logo: /assets/FeliciaHester_ProfilePhoto.jpeg
description: MIT trained Data Analyst. Connecting data dots using Python & Excel formulas.\
Telling the data story using logic & creativity.
#
#
#
show_downloads: false
remote_theme: "pages-themes/minimal@v0.2.0"


