# at top
title: Felicia Hester

# picture
logo: /assets/FeliciaHester_ProfilePhoto.jpeg

#under picture
description: 

# skip 
nothing:

# skip 
show_downloads: false

#skip
nothing:

<script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
<div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="dark" data-type="VERTICAL" data-vanity="feliciadhester" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://www.linkedin.com/in/feliciadhester?trk=profile-badge">Felicia Davis Hester</a></div>
              

google_analytics: |
  baseurl: /portfolio 
  url: https://feliciahester.github.io/
 
# skip
nothing:

#skip
theme: jekyll-theme-minimal

# skip 

# skip 

# skip 

# skip 

# skip 

# skip 

# skip 

# skip 

# skip 

# skip 

# Site Author
author:
  name: Felicia Hester
  picture: /assets/FeliciaHester_ProfilePhoto.jpeg
  links:
    - title: GitHub
      url: https://feliciahester.github.io/portfolio/
      # icon: fab fa-github-square

