title: Felicia Hester
logo: 
description: MIT trained Data Analyst. Connecting data dots using Python & Excel formulas. Telling the data story using logic & creativity.
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
